language: node_js
node_js: stable
install:
- npm install
before_install:
- npm install -g hexo
- npm install -g hexo-cli
befor_script:
- sed -i'' "s~git@github.com:WangYX321/WangYX321.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/WangYX321/WangYX321.gihub.io.git~"
  _config.yml
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
after_script:
- cd ./public
- git init
- git config user.name "WangYX321"
- git config user.email "596868981@qq.com"
- git add .
- git commit -m "Update docs"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
branches:
  only:
  - blog-source
env:
  global:
  - GH_REF: github.com/WangYX321/WangYX321.github.io.git
  - secure: foppUe9IXvH+0y+jLNIyQ2gMAtyDKSrFho4UL7i8HxaMloA4VKMqodEJSOzmhRA35jdWa+bskMm+LxKdx5xrJI8uO3x2JYf5bP1ibNPY5CJk3+T1VOrbzZcJUdIO3Qhvnu4IAXmkCFU1BLZF1nr4HoIulEg4TPaS8iQrcsfqAezo90TFHpAmegrhAwSPmqWd40vuEGTyFWOJdciDsW0pDaqKchU4KEPut94erOpywNhasRrjRkE9grkzn0CsuNt/wikuOYWO+5rJ2Q2QhYsfk75la81FLuS9z3MjPjBF2Auho61c0+Zid2GPjEuuv3fINmAq+LCna120gg2HRlJ5Kwo7YM+CH27Mjys2Hr+rXWjFOkEP1/kYLlsTP1l/3k5USsDfMXe7z7Q00X70D4hDoqsu5aulYqoM5S20DzFPVmk1hYMDID9O6IqNfd6TRO86GphvYSh5Lb5f1T+3sQksYnrPEvy2WcRlLn+rfDzVpdHMthCcdm6nheJpswpAbOh2iFEOa1XYUG25GZm8l5RFwLmCqf0OnyfL//XSsAc4dQym0IkGYUNbCHDo/cV3TP2tqDmK2oqblytQJLNQ/e4CDNw6xJn0VmAi32XeItjNSpYdfzLFZPJQHPNMaQ0gnroli17z6S2iBMO1qT+3sNlbWjkLjfIPDlCEVzZqYril9q4=
